#!/bin/bash
# =============================================================================
# ARI V3 - Complete Setup Script
# =============================================================================
# This script runs all setup steps in order:
# 1. Qdrant vector database
# 2. Neo4j graph database
# 3. Python virtual environment
# 4. Environment file template
#
# Run this script from the ari_v3/setup directory.
# =============================================================================

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ARI_V3_DIR="$(dirname "$SCRIPT_DIR")"

echo -e "${BLUE}=============================================="
echo "ARI V3 - Complete Setup"
echo "==============================================${NC}"
echo ""
echo "This script will set up:"
echo "  1. Qdrant vector database (Docker)"
echo "  2. Neo4j graph database (Docker)"
echo "  3. Python virtual environment"
echo "  4. Environment configuration file"
echo ""
echo "Prerequisites:"
echo "  - Docker installed and running"
echo "  - Python 3.10+ installed"
echo "  - OpenAI API key ready"
echo ""
read -p "Press Enter to continue or Ctrl+C to cancel..."
echo ""

# -----------------------------------------------------------------------------
# Step 1: Setup Qdrant
# -----------------------------------------------------------------------------
echo -e "${BLUE}[Step 1/4] Setting up Qdrant...${NC}"
echo ""

chmod +x "$SCRIPT_DIR/setup_qdrant.sh"
"$SCRIPT_DIR/setup_qdrant.sh"

echo ""
echo -e "${GREEN}Qdrant setup complete.${NC}"
echo ""
read -p "Press Enter to continue to Neo4j setup..."
echo ""

# -----------------------------------------------------------------------------
# Step 2: Setup Neo4j
# -----------------------------------------------------------------------------
echo -e "${BLUE}[Step 2/4] Setting up Neo4j...${NC}"
echo ""

chmod +x "$SCRIPT_DIR/setup_neo4j.sh"
"$SCRIPT_DIR/setup_neo4j.sh"

echo ""
echo -e "${GREEN}Neo4j setup complete.${NC}"
echo ""
read -p "Press Enter to continue to Python setup..."
echo ""

# -----------------------------------------------------------------------------
# Step 3: Setup Python Virtual Environment
# -----------------------------------------------------------------------------
echo -e "${BLUE}[Step 3/4] Setting up Python virtual environment...${NC}"
echo ""

cd "$ARI_V3_DIR"

if [ -d "venv" ]; then
    echo -e "${YELLOW}Virtual environment already exists at ${ARI_V3_DIR}/venv${NC}"
    read -p "Do you want to recreate it? (y/N): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf venv
        python3 -m venv venv
    fi
else
    python3 -m venv venv
fi

echo "Activating virtual environment..."
source venv/bin/activate

echo "Installing Python packages..."
pip install --upgrade pip
pip install -r setup/requirements.txt

echo ""
echo -e "${GREEN}Python setup complete.${NC}"
echo ""

# -----------------------------------------------------------------------------
# Step 4: Create Environment File
# -----------------------------------------------------------------------------
echo -e "${BLUE}[Step 4/4] Setting up environment file...${NC}"
echo ""

if [ -f "$ARI_V3_DIR/.env" ]; then
    echo -e "${YELLOW}.env file already exists at ${ARI_V3_DIR}/.env${NC}"
    echo "Keeping existing file."
else
    cat > "$ARI_V3_DIR/.env" << 'ENVFILE'
# ARI V3 Environment Configuration
# Generated by setup_all.sh - edit this file with your settings

# =============================================================================
# REQUIRED - You must set these
# =============================================================================

# OpenAI API Key - get one at https://platform.openai.com/api-keys
OPENAI_API_KEY=sk-your-openai-api-key-here

# =============================================================================
# Database Connections - defaults work with setup scripts
# =============================================================================

# Neo4j Graph Database
NEO4J_URI=bolt://localhost:7687
NEO4J_URL=bolt://localhost:7687
NEO4J_USERNAME=neo4j
NEO4J_USER=neo4j
NEO4J_PASSWORD=ari_secure_password_2024
NEO4J_DATABASE=neo4j

# Qdrant Vector Database
QDRANT_URL=http://localhost:6333
QDRANT_HOST=localhost
QDRANT_PORT=6333
QDRANT_COLLECTION_NAME=fashion_products
QDRANT_VISUAL_COLLECTION_NAME=fashion_multimodal_embeddings

# =============================================================================
# Optional Settings
# =============================================================================

ENVIRONMENT=development
LOG_LEVEL=INFO
OPENAI_MODEL=gpt-4o-mini
OPENAI_EMBEDDING_MODEL=text-embedding-3-small
ENABLE_VISUAL_INTELLIGENCE=true
ENABLE_SEMANTIC_SEARCH=true
ENVFILE

    echo "Created ${ARI_V3_DIR}/.env"
    echo ""
    echo -e "${YELLOW}IMPORTANT: Edit .env and add your OpenAI API key!${NC}"
fi

echo ""

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo -e "${GREEN}=============================================="
echo "Setup Complete!"
echo "==============================================${NC}"
echo ""
echo "Services running:"
echo "  - Qdrant:  http://localhost:6333/dashboard"
echo "  - Neo4j:   http://localhost:7474 (neo4j / ari_secure_password_2024)"
echo ""
echo "Next steps:"
echo ""
echo "  1. Edit your OpenAI API key:"
echo "     nano ${ARI_V3_DIR}/.env"
echo ""
echo "  2. Activate the virtual environment:"
echo "     source ${ARI_V3_DIR}/venv/bin/activate"
echo ""
echo "  3. Run the CLI demo:"
echo "     cd ${ARI_V3_DIR}"
echo "     python demo_cli.py"
echo ""
echo "  4. Or run the web interface:"
echo "     streamlit run web_app.py"
echo ""
echo "For more details, see: ${SCRIPT_DIR}/SETUP.md"
echo ""
